---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: logos
version: 1
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/blue-build/base-images/fedora-base
image-version: latest # You can pin to a specific version of Fedora as well

# module configuration, executed in order
# you can include multiple instances of the same module
modules:

  - type: dnf
    repos:
      nonfree: rpmfusion
    skip-dependencies: true
    install:
          packages:
        - fastfetch
        - ly
        - wayland
        - wayland-protocols
        - wlroots
        - labwc
        - grim
        - swaybg
        - swaybar
        - fuzzel
        - foot
        
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: user
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - app.zen_browser.zen
  
  - type: brew
    brew-analytics: false
    

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
